---
Name: goldfinch-focuspoint-extra
---

SilverStripe\Assets\File:
  extensions:
    - Goldfinch\FocusPointExtra\Extensions\FileFocusPointExtension

SilverStripe\Assets\Image:
  extensions:
    - Goldfinch\FocusPointExtra\Extensions\ImageExtension
