---
Name: goldfinch-image-editor
---
SilverStripe\Assets\File:
  extensions:
    - Goldfinch\ImageEditor\Extensions\FileFocusPointExtension

SilverStripe\Assets\Image:
  extensions:
    - Goldfinch\ImageEditor\Extensions\ImageExtension

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - "goldfinch/image-editor:client/dist/resources/assets/image-editor-style.css"
  extra_requirements_javascript:
    - "goldfinch/image-editor:client/dist/resources/assets/image-editor.js"

---
Name: goldfinch-image-editor-admin-icon
Only:
  moduleexists: "goldfinch/enchantment"
---
Goldfinch\ImageEditor\Admin\ImageEditorAdmin:
  menu_icon_class: "bi-images"
