---
Name: goldfinch-image-settings
---
SilverStripe\Assets\File:
  extensions:
    - Goldfinch\ImageSettings\Extensions\FileFocusPointExtension

SilverStripe\Assets\Image:
  extensions:
    - Goldfinch\ImageSettings\Extensions\ImageExtension

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - "goldfinch/image-settings:client/dist/resources/assets/image-settings-style.css"
  extra_requirements_javascript:
    - "goldfinch/image-settings:client/dist/resources/assets/image-settings.js"
